[42기 장주성] add: kakao-login 기능 구현
wecode-bootcamp-korea/42-2nd-smallbox-backend pull request #8
Opened 2023-02-28 10:04 UTC by jangjuseong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- add: kakao-login 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- add: kakao-login 기능 구현
- unit-test 완료
- auth.js 검증 미들웨어 추가

<br />

## :: 테스트 결과 이미지

<br />

## :: 기타 질문 및 특이 사항
- jest unit-test 시 error message 관련 matcher를 찾아봐도 잘 모르겠습니다...

2023-03-01 21:21 UTC, Jon9Beom commented on app.js
> +
해당 코드의 위치가 수정된 이유를 알 수 있을까요? 코드상 next function을 통해 존재하지 않은 엔드포인트에 대해 요청이 들어올 때, express에서 다음 미들웨어로 에러 객체를 만들어 넘기고 있기 때문에 이전처럼 `routes`와 `globalErrorHandler` 미들웨어 사이에 있어야 올바르게 동작하지 않을까 싶습니다.

2023-03-01 21:21 UTC, Jon9Beom commented on middlewares/auth.js
> +};
아래를 참고하여 만들었던 catchAsync()를 활용하는 등, 조금 더 디테일한 인가 처리 미들웨어가 되면 좋을 것 같습니다.
디테일한 부분은 다를 수 있으니 참고만 하고 주성님 코드에 적절하게 적용시켜주세요!
```javascript
const jwt = require('jsonwebtoken')

const userDao  = require('../services/userDao')
const { catchAsync } = require('../utils/error')

const loginRequired = catchAsync(async (req, res, next) => {

  // 1) Getting token and check of it's there
  const accessToken = req.headers.authorization

	if (!accessToken) {
		const error = new Error('NEED_ACCESS_TOKEN')
		error.statusCode = 401
		
		return next(error)
	}

  // 2) Verification token
  const decoded = await jwt.verify(accessToken, process.env.JWT_SECRET);

  // 3) Check if user still exists
	const user = await userDao.getUserById(decoded.id)

	if (!user) {
		const error = new Error('USER_DOES_NOT_EXIST')
		error.statusCode = 404
		
		return next(error)
	}

  // 4) GRANT ACCESS
  req.user = user;
  next();
})

module.exports = { loginRequired }

```

2023-03-01 21:21 UTC, Jon9Beom commented on models/userDao.js
> +};
INSERT INTO 부분에서 social_type_id가 하드코딩 되어 있는데, 이러한 코드는 지양하는 것이 좋습니다. api 코드 혹은 database schema를 포함해서 모든 작업들은, 해당프로젝트에 처음 투입되는 누가 보더라도 가장 직관적이게 알 수 있는, 유지 보수하기 용이한 코드를 작성하도록 노력해야합니다. 따라서 우리만 의미를 알 수 있는 하드 코딩 보다는, 상수형 데이터의 열거 집합인 enum이라는 개념을 활용하여 수정해주세요.

또한 위의 경우 객체가 수정될 수 있기 때문에 상수 데이터 관리 목적과는 반대되는 경우가 발생할 수 있습니다. 따라서 JavaScript의 `Object.freeze()`를 활용합니다.
```javascript
const SocialTypes = Object.freeze({
  KAKAO : 1,
  NAVER : 2,
  GOOGLE : 3,
  APPLE : 4
})

. . . 

await appDataSource.query(`
  . . . 
`, [ . . . , SocialTypes.KAKAO, . . .] );
```

2023-03-01 21:21 UTC, Jon9Beom commented on tests/users.test.js
> +  });
새로운 계정이 만들어지는 if문만 검증하는것이 아닌, 기존에 존재하던 카카오 유저의 로그인도 검증 할 수 있는 테스트 케이스가 필요합니다. 때에 따라서 api 코드 상에서 statusCode를 분리하여 작성하는것이 테스트에서도 용이하고 REST한 statusCode를 응답해 줄 수 있습니다!

2023-03-02 02:42 UTC, jangjuseong commented on app.js
> +
헬스체크 코드가 app.all('*) 코드 밑에 있어서 핑퐁 통신이 안돼서 수정했었습니다.

순서를
routes
/ping
app.all('*')
globalErrorHandler
순서로 하도록 하겠습니다!

2023-03-02 10:50 UTC, Kang-kyunghun requested changes

2023-03-02 10:50 UTC, Kang-kyunghun commented on controllers/userController.js
> +  console.log(code, accessToken);
불필요한 console.log는 제거해 주세요.

2023-03-02 10:50 UTC, Kang-kyunghun commented on db/migrations/20230301123219_alter_theater_seats_table.sql
> +ALTER TABLE `theater_seats` DROP CONSTRAINT `theater_seats_theater_seat_status_id_fk`;
db 스키마 관련 코드는 따로 분리해서 올려주세요.

2023-03-02 10:50 UTC, Kang-kyunghun commented on tests/users.test.js
> +    expect(response.statusCode).toEqual(500);
혹시 500이 나는 상황이 언제 일까요?
500이 나는 상황을 코드상에 일부로 유도 했다면 해당 코드의 status code를 400번대의 코드로 수정해 주세요.

2023-03-02 10:50 UTC, Kang-kyunghun commented on services/userService.js
> +      expiresIn: process.env.JWT_EXPIRES_IN,
1. JWT 만들 때 kakaoId가 아닌, userId로 만들어 주세요.
2. 조건문을 만족할 때와 아닐 때 JWT를 만드는 코드가 중복되는데, 해당 코드가 어떻게 하면 중복되지 않게 할 수 있을지 고민해 보고 줄여보면 좋을 것 같습니다.

2023-03-02 10:50 UTC, Kang-kyunghun commented on models/userDao.js
> +    [
인덱스가 너무 넓은 것 같은데, 한 번 확인해 주세요.

2023-03-03 01:50 UTC, Jon9Beom commented on controllers/userController.js
> +  res.status(code).json({ accessToken });
잘 반영해주셨네요!! 👍 다만 아래와 같이 구조분해 할당을 활용하면 코드 라인을 줄일 수 있을 것 같네요

```suggestion
  const { statusCode, accessToken } = await userService.kakaoLogin(kakaoToken);
  
  res.status(statusCode).json({ accessToken });
```

2023-03-03 09:10 UTC, Jon9Beom commented
LGTM 👍 추후에 계속해서 리팩토링 꼭 가져주세요!

2023-03-03 09:10 UTC, merged